spring:
    application:
        name: consumer-service
    cloud:
        stream:
            kafka:
                binder:
                    # 9092 is the default port of Kafka
                    brokers: localhost:9092
            bindings:
                # https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/functional-binding-names.html
                # Format: <method name>-<in or out>-<index>
                # receiveMessage: name of the method that receives the message
                # in: because is a consumer
                # 0: Index of the binding. This allows the same method to receive from multiple queues
                receiveMessage-in-0:
                    destination: ms-example-queue
                    # Group is necessary to ensure that this
                    # consumer receives all messages sent while
                    # it was offline
                    group: my-consumer-group

eureka:
    client:
    # To report to Eureka when this service is up
        registerWithEureka: true
    # Eureka server URL
        service-url:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    instance:
    # To avoid using DNS
        prefer-ip-address: true

server:
    port: 8083