spring:
    application:
        name: product-service
    cloud:
        stream:
            kafka:
                binder:
                # 9092 is the default port of Kafka
                    brokers: localhost:9092
            bindings:
                # https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/functional-binding-names.html
                # Format: <method name>-<in or out>-<index>
                # sendMessage: name of the method that sends the message
                # out: because is a consumer
                # 0: Index of the binding. This makes sense when the same method sends to multiple queues
                sendMessage-out-0:
                    #Name of the queue that will manage the messages
                    destination: ms-example-queue

eureka:
    client:
    # To report to Eureka when this service is up
        registerWithEureka: true
    # Eureka server URL
        service-url:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    instance:
    # To avoid using DNS
        prefer-ip-address: true

server:
    port: 8084