spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      # Integration with eureka to automatically discover all the routes
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          # Indicates the URL of the Keycloak endpoint that provides the keys to verify JWT tokens        
          # This is used within the subnet where the microservices are deployed
          # This URL does not need to be accessible from outside
          jwk-set-uri: http://localhost:9000/realms/myrealm/protocol/openid-connect/certs

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
      
  info:
    env:
      enabled: true

# App metadata
info:
  app:
    name: Gateway server
    description: Gateway server
    version: 1.0.0
  company:
    name: MyCompany
    contact:
      email: support@mycompany.com
      phone: +1234567890
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}